version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    env_file:
      - ./db/postgres/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./db/init:/docker-entrypoint-initdb.d
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: my-pgadmin
    env_file:
      - ./db/pgadmin/.env
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./db/pgadmin/servers.json:/pgadmin4/servers.json  # TODO: make this readonly
    restart: unless-stopped

  backend:
    image: rooman-backend
    pull_policy: never
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: runner
    container_name: rooman-backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    image: rooman-frontend
    pull_policy: never
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: runner
    container_name: rooman-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:
